/**
 * SignalOps active control_id registry.
 *
 * Every entry in `controls` maps to a rendered, user-actionable control in
 * the frontend today. IDs used only for planned/future backend integration
 * live in `plannedControls` and MUST NOT be counted as active, missing or
 * dead by the reconciliation checker (`scripts/check-controls.mjs`).
 *
 * Each active control belongs to exactly one category, determined by how
 * it is wired at its call site:
 *   - `controlId={controls.X.Y}` on <BackendRequiredDialog> → backend-required-truthful
 *   - `data-control-id={controls.X.Y}` on a rendered element → frontend-functional
 */

export const controls = {
  shell: {
    sidebarToggle: "shell.sidebar.toggle",
    accountScopeOpen: "shell.account_scope.open",
    accountScopeSelectAll: "shell.account_scope.select_all",
    accountScopeSelectExact: "shell.account_scope.select_exact",
    accountScopePin: "shell.account_scope.pin",
    languageToggle: "shell.language.toggle",
    privacyToggle: "shell.privacy.toggle",
    inboxOpen: "shell.inbox.open",
    refresh: "shell.refresh",
    exportOpen: "shell.export.open",
    shareOpen: "shell.share.open",
    shareHideSensitive: "shell.share.hide_sensitive",
    pageTitle: "shell.page_title",
    lastUpdated: "shell.last_updated",
    timeRange: "shell.time_range",
    overflow: "shell.overflow",
  },
  dashboard: {
    carouselPrev: "dashboard.carousel.prev",
    carouselNext: "dashboard.carousel.next",
    carouselPlayPause: "dashboard.carousel.play_pause",
    carouselScrub: "dashboard.carousel.scrub",
    heatmapBucketOpen: "dashboard.heatmap.bucket_open",
    riskOpen: "dashboard.risk.open",
    sourcesViewAll: "dashboard.sources.view_all",
    ordersViewAll: "dashboard.orders.view_all",
  },
  accounts: {
    tabActive: "accounts.tab.active",
    tabArchive: "accounts.tab.archive",
    search: "accounts.search",
    add: "accounts.add",
    verify: "accounts.verify",
    refresh: "accounts.refresh",
    edit: "accounts.edit",
    pin: "accounts.pin",
    archive: "accounts.archive",
    restore: "accounts.restore",
    
    activationOpen: "accounts.activation.open",
    nativeCurrencyReview: "accounts.native_currency.review",
  },
  sources: {
    tabActive: "sources.tab.active",
    tabPerformance: "sources.tab.performance",
    tabArchive: "sources.tab.archive",
    tabMatrix: "sources.tab.matrix",
    search: "sources.search",
    add: "sources.add",
    import: "sources.import",
    export: "sources.export",
    verify: "sources.verify",
    edit: "sources.edit",
    toggle: "sources.toggle",
    archive: "sources.archive",
    restore: "sources.restore",
    
    accountMatrixOpen: "sources.account_matrix.open",
  },
  signals: {
    filterStatus: "signals.filter.status",
    search: "signals.search",
    openDetail: "signals.open_detail",
    openTrace: "signals.open_trace",
    copyCorrelation: "signals.copy_correlation",
    openOrders: "signals.open_orders",
    inspectParser: "signals.inspect_parser",
  },
  positions: {
    refresh: "positions.refresh",
    filterAccount: "positions.filter.account",
    filterSymbol: "positions.filter.symbol",
    filterSide: "positions.filter.side",
    openSignal: "positions.open_signal",
    openTrace: "positions.open_trace",
    export: "positions.export",
  },
  orders: {
    filterAccount: "orders.filter.account",
    filterSymbol: "orders.filter.symbol",
    filterSide: "orders.filter.side",
    filterResult: "orders.filter.result",
    search: "orders.search",
    pageSize: "orders.page_size",
    openTrace: "orders.open_trace",
    exportCsv: "orders.export_csv",
    exportJson: "orders.export_json",
  },
  risk: {
    accountScope: "risk.account_scope",
    previewImpact: "risk.preview_impact",
    compareVersions: "risk.compare_versions",
    apply: "risk.apply",
    restoreVersion: "risk.restore_version",
    export: "risk.export",
  },
  telegram: {
    apiIdEdit: "telegram.api_id.edit",
    apiHashEdit: "telegram.api_hash.edit",
    configSave: "telegram.config.save",
    sendCode: "telegram.send_code",
    otpSubmit: "telegram.otp.submit",
    twoFaSubmit: "telegram.2fa.submit",
    authCancel: "telegram.auth.cancel",
    testReadonly: "telegram.test_readonly",
    reconnect: "telegram.reconnect",
    revoke: "telegram.revoke",
    identityOpen: "telegram.identity.open",
    sourcesOpen: "telegram.sources.open",
    inboxOpen: "telegram.inbox.open",
  },
  runtime: {
    tabOverview: "runtime.tab.overview",
    tabComponents: "runtime.tab.components",
    tabProviders: "runtime.tab.providers",
    tabVersions: "runtime.tab.versions",
    tabLogs: "runtime.tab.logs",
    refresh: "runtime.refresh",
    selfTest: "runtime.self_test",
    logsOpen: "runtime.logs.open",
    componentRestart: "runtime.component.restart",
    updateOpen: "runtime.update.open",
    rollbackOpen: "runtime.rollback.open",
  },
  analysisProviders: {
    add: "analysis_providers.add",
    edit: "analysis_providers.edit",
    test: "analysis_providers.test",
    assignSlot: "analysis_providers.assign_slot",
    enable: "analysis_providers.enable",
    disable: "analysis_providers.disable",
    archive: "analysis_providers.archive",
    restore: "analysis_providers.restore",
    
    routingPolicy: "analysis_providers.routing_policy",
    switchPreview: "analysis_providers.switch_preview",
    activate: "analysis_providers.activate",
  },
  hermes: {
    tabOverview: "hermes.tab.overview",
    tabAccounts: "hermes.tab.accounts",
    tabSources: "hermes.tab.sources",
    tabDecisions: "hermes.tab.decisions",
    tabLearning: "hermes.tab.learning",
    tabPolicies: "hermes.tab.policies",
    tabTrace: "hermes.tab.trace",
    tabPrompts: "hermes.prompts.tab",
    activationPreview: "hermes.activation.preview",
    activationOpen: "hermes.activation.open",
    recommendationOpen: "hermes.recommendation.open",
    datasetOpen: "hermes.dataset.open",
  },
  inbox: {
    filterSeverity: "inbox.filter.severity",
    filterComponent: "inbox.filter.component",
    filterState: "inbox.filter.state",
    openDetail: "inbox.open_detail",
    provideInput: "inbox.provide_input",
    recheck: "inbox.recheck",
    copyCorrelation: "inbox.copy_correlation",
    exportEvidence: "inbox.export_evidence",
  },
  trace: {
    search: "trace.search",
    copyId: "trace.copy_id",
    openSignal: "trace.open_signal",
    openOrder: "trace.open_order",
    exportJson: "trace.export_json",
    exportCsv: "trace.export_csv",
  },
} as const;

/**
 * Reserved for planned backend integration. NOT rendered today. The
 * reconciliation checker must not count these as active/missing/dead.
 * Preserved so Codex can wire concrete backend endpoints later.
 */
export const plannedControls = {
  shell: {
    healthOpen: "shell.health.open",
  },
  dashboard: {
    kpiPnl: "dashboard.kpi.pnl.open",
    kpiIncome: "dashboard.kpi.income.open",
    kpiExposure: "dashboard.kpi.exposure.open",
    kpiExecution: "dashboard.kpi.execution.open",
    heatmapResize: "dashboard.heatmap.resize",
    heatmapDensity: "dashboard.heatmap.density",
    sourcesSort: "dashboard.sources.sort",
  },
  accounts: {
    openDetails: "accounts.open_details",
    riskAmountEdit: "accounts.risk_amount_per_order.edit",
    sourceMatrixOpen: "accounts.source_matrix.open",
    accountLineOpen: "accounts.account_line.open",
    instrumentMappingOpen: "accounts.instrument_mapping.open",
    deletePermanent: "accounts.delete_permanent",
  },
  sources: {
    filterGroup: "sources.filter.group",
    filterState: "sources.filter.state",
    filterSymbol: "sources.filter.symbol",
    performanceOpen: "sources.performance.open",
    historyOpen: "sources.history.open",
    instrumentMatrixOpen: "sources.instrument_matrix.open",
    deletePermanent: "sources.delete_permanent",
  },
  signals: {
    filterDate: "signals.filter.date",
    filterAccount: "signals.filter.account",
    filterSource: "signals.filter.source",
    filterSymbol: "signals.filter.symbol",
    filterParser: "signals.filter.parser",
    timeRangeOpen: "signals.time_range.open",
    openOriginal: "signals.open_original",
  },
  positions: {
    filterSource: "positions.filter.source",
    openDetail: "positions.open_detail",
  },
  orders: {
    filterHour: "orders.filter.hour",
    filterSource: "orders.filter.source",
    filterStatus: "orders.filter.status",
    openDetail: "orders.open_detail",
    openSignal: "orders.open_signal",
    copyTicket: "orders.copy_ticket",
    copyCorrelation: "orders.copy_correlation",
  },
  risk: {
    editDraft: "risk.edit_draft",
  },
  telegram: {
    configChange: "telegram.config.change",
  },
  runtime: {
    inboxOpen: "runtime.inbox.open",
    reconcilerOpen: "runtime.reconciler.open",
    readinessReducerOpen: "runtime.readiness_reducer.open",
    accountLineFactoryOpen: "runtime.account_line_factory.open",
  },
  analysisProviders: {
    reorder: "analysis_providers.reorder",
    logs: "analysis_providers.logs",
    inbox: "analysis_providers.inbox",
    deletePermanent: "analysis_providers.delete_permanent",
  },
  hermes: {
    evidenceOpen: "hermes.evidence.open",
    modelSelect: "hermes.model.select",
    sourcesSelect: "hermes.sources.select",
    datasetsSelect: "hermes.datasets.select",
    promptAdd: "hermes.prompts.add",
    promptDuplicate: "hermes.prompts.duplicate",
    promptEdit: "hermes.prompts.edit",
    promptPreview: "hermes.prompts.preview",
    promptEvaluate: "hermes.prompts.evaluate",
    promptCompare: "hermes.prompts.compare",
    promptPublish: "hermes.prompts.publish",
    promptArchive: "hermes.prompts.archive",
    promptRestore: "hermes.prompts.restore",
    promptDeletePermanent: "hermes.prompts.delete_permanent",
    promptExport: "hermes.prompts.export",
    promptTrace: "hermes.prompts.trace",
  },
  inbox: {
    filterAccount: "inbox.filter.account",
    filterSource: "inbox.filter.source",
    filterDate: "inbox.filter.date",
    openEntity: "inbox.open_entity",
    openTrace: "inbox.open_trace",
  },
  trace: {
    filterAccount: "trace.filter.account",
    filterSource: "trace.filter.source",
    filterSignal: "trace.filter.signal",
    filterOrder: "trace.filter.order",
    filterComponent: "trace.filter.component",
    filterDate: "trace.filter.date",
    openAccount: "trace.open_account",
    openSource: "trace.open_source",
  },
} as const;
