/**
 * Stable control_id registry from docs/genesis-pack/04_CONTROL_INVENTORY.md.
 * Apply via <button data-control-id={controls.dashboard.refresh}>… so Codex
 * can map every UI control to a backend adapter later without ambiguity.
 */

export const controls = {
  shell: {
    sidebarToggle: "shell.sidebar.toggle",
    accountScopeOpen: "shell.account_scope.open",
    accountScopeSelectAll: "shell.account_scope.select_all",
    accountScopeSelectExact: "shell.account_scope.select_exact",
    accountScopePin: "shell.account_scope.pin",
    languageToggle: "shell.language.toggle",
    privacyToggle: "shell.privacy.toggle",
    inboxOpen: "shell.inbox.open",
    healthOpen: "shell.health.open",
    refresh: "shell.refresh",
    exportOpen: "shell.export.open",
    shareOpen: "shell.share.open",
    shareHideSensitive: "shell.share.hide_sensitive",
  },
  dashboard: {
    timeToday: "dashboard.time.today",
    timeYesterday: "dashboard.time.yesterday",
    time7d: "dashboard.time.7d",
    time30d: "dashboard.time.30d",
    time90d: "dashboard.time.90d",
    timeMtd: "dashboard.time.mtd",
    timeYtd: "dashboard.time.ytd",
    timeCustom: "dashboard.time.custom",
    kpiPnl: "dashboard.kpi.pnl.open",
    kpiIncome: "dashboard.kpi.income.open",
    kpiExposure: "dashboard.kpi.exposure.open",
    kpiExecution: "dashboard.kpi.execution.open",
    carouselPrev: "dashboard.carousel.prev",
    carouselNext: "dashboard.carousel.next",
    carouselPlayPause: "dashboard.carousel.play_pause",
    carouselScrub: "dashboard.carousel.scrub",
    heatmapBucketOpen: "dashboard.heatmap.bucket_open",
    riskOpen: "dashboard.risk.open",
    sourcesSort: "dashboard.sources.sort",
    sourcesViewAll: "dashboard.sources.view_all",
    ordersViewAll: "dashboard.orders.view_all",
  },
  accounts: {
    tabActive: "accounts.tab.active",
    tabArchive: "accounts.tab.archive",
    search: "accounts.search",
    add: "accounts.add",
    verify: "accounts.verify",
    refresh: "accounts.refresh",
    edit: "accounts.edit",
    pin: "accounts.pin",
    archive: "accounts.archive",
    restore: "accounts.restore",
    deletePermanent: "accounts.delete_permanent",
    openDetails: "accounts.open_details",
    activationOpen: "accounts.activation.open",
  },
  sources: {
    tabActive: "sources.tab.active",
    tabPerformance: "sources.tab.performance",
    tabArchive: "sources.tab.archive",
    search: "sources.search",
    filterGroup: "sources.filter.group",
    filterState: "sources.filter.state",
    filterSymbol: "sources.filter.symbol",
    add: "sources.add",
    import: "sources.import",
    export: "sources.export",
    verify: "sources.verify",
    edit: "sources.edit",
    toggle: "sources.toggle",
    archive: "sources.archive",
    restore: "sources.restore",
    deletePermanent: "sources.delete_permanent",
    performanceOpen: "sources.performance.open",
    historyOpen: "sources.history.open",
  },
  signals: {
    filterDate: "signals.filter.date",
    filterAccount: "signals.filter.account",
    filterSource: "signals.filter.source",
    filterSymbol: "signals.filter.symbol",
    filterStatus: "signals.filter.status",
    filterParser: "signals.filter.parser",
    search: "signals.search",
    openDetail: "signals.open_detail",
    openOriginal: "signals.open_original",
    openTrace: "signals.open_trace",
    copyCorrelation: "signals.copy_correlation",
    openOrders: "signals.open_orders",
    inspectParser: "signals.inspect_parser",
  },
  positions: {
    refresh: "positions.refresh",
    filterAccount: "positions.filter.account",
    filterSource: "positions.filter.source",
    filterSymbol: "positions.filter.symbol",
    filterSide: "positions.filter.side",
    openDetail: "positions.open_detail",
    openSignal: "positions.open_signal",
    openTrace: "positions.open_trace",
    export: "positions.export",
  },
  orders: {
    timeToday: "orders.time.today",
    timeYesterday: "orders.time.yesterday",
    time7d: "orders.time.7d",
    time30d: "orders.time.30d",
    time90d: "orders.time.90d",
    timeMtd: "orders.time.mtd",
    timeYtd: "orders.time.ytd",
    timeCustom: "orders.time.custom",
    filterHour: "orders.filter.hour",
    filterAccount: "orders.filter.account",
    filterSource: "orders.filter.source",
    filterSymbol: "orders.filter.symbol",
    filterSide: "orders.filter.side",
    filterResult: "orders.filter.result",
    filterStatus: "orders.filter.status",
    search: "orders.search",
    pageSize: "orders.page_size",
    openDetail: "orders.open_detail",
    openSignal: "orders.open_signal",
    openTrace: "orders.open_trace",
    copyTicket: "orders.copy_ticket",
    copyCorrelation: "orders.copy_correlation",
    exportCsv: "orders.export_csv",
    exportJson: "orders.export_json",
  },
  risk: {
    accountScope: "risk.account_scope",
    editDraft: "risk.edit_draft",
    previewImpact: "risk.preview_impact",
    compareVersions: "risk.compare_versions",
    apply: "risk.apply",
    restoreVersion: "risk.restore_version",
    export: "risk.export",
  },
  telegram: {
    apiIdEdit: "telegram.api_id.edit",
    apiHashEdit: "telegram.api_hash.edit",
    configSave: "telegram.config.save",
    sendCode: "telegram.send_code",
    otpSubmit: "telegram.otp.submit",
    twoFaSubmit: "telegram.2fa.submit",
    authCancel: "telegram.auth.cancel",
    testReadonly: "telegram.test_readonly",
    reconnect: "telegram.reconnect",
    revoke: "telegram.revoke",
    identityOpen: "telegram.identity.open",
    sourcesOpen: "telegram.sources.open",
    inboxOpen: "telegram.inbox.open",
  },
  runtime: {
    tabOverview: "runtime.tab.overview",
    tabComponents: "runtime.tab.components",
    tabProviders: "runtime.tab.providers",
    tabVersions: "runtime.tab.versions",
    tabLogs: "runtime.tab.logs",
    refresh: "runtime.refresh",
    selfTest: "runtime.self_test",
    logsOpen: "runtime.logs.open",
    componentRestart: "runtime.component.restart",
    inboxOpen: "runtime.inbox.open",
    updateOpen: "runtime.update.open",
    rollbackOpen: "runtime.rollback.open",
  },
  providers: {
    add: "providers.add",
    test: "providers.test",
    edit: "providers.edit",
    switchPreview: "providers.switch_preview",
    activate: "providers.activate",
    deactivate: "providers.deactivate",
    archive: "providers.archive",
    restore: "providers.restore",
    deletePermanent: "providers.delete_permanent",
  },
  hermes: {
    tabOverview: "hermes.tab.overview",
    tabAccounts: "hermes.tab.accounts",
    tabSources: "hermes.tab.sources",
    tabDecisions: "hermes.tab.decisions",
    tabLearning: "hermes.tab.learning",
    tabPolicies: "hermes.tab.policies",
    tabTrace: "hermes.tab.trace",
    activationPreview: "hermes.activation.preview",
    activationOpen: "hermes.activation.open",
    recommendationOpen: "hermes.recommendation.open",
    evidenceOpen: "hermes.evidence.open",
    datasetOpen: "hermes.dataset.open",
  },
  inbox: {
    filterSeverity: "inbox.filter.severity",
    filterComponent: "inbox.filter.component",
    filterAccount: "inbox.filter.account",
    filterSource: "inbox.filter.source",
    filterDate: "inbox.filter.date",
    filterState: "inbox.filter.state",
    openDetail: "inbox.open_detail",
    openEntity: "inbox.open_entity",
    provideInput: "inbox.provide_input",
    recheck: "inbox.recheck",
    openTrace: "inbox.open_trace",
    copyCorrelation: "inbox.copy_correlation",
    exportEvidence: "inbox.export_evidence",
  },
  trace: {
    search: "trace.search",
    filterAccount: "trace.filter.account",
    filterSource: "trace.filter.source",
    filterSignal: "trace.filter.signal",
    filterOrder: "trace.filter.order",
    filterComponent: "trace.filter.component",
    filterDate: "trace.filter.date",
    copyId: "trace.copy_id",
    openAccount: "trace.open_account",
    openSource: "trace.open_source",
    openSignal: "trace.open_signal",
    openOrder: "trace.open_order",
    exportJson: "trace.export_json",
    exportCsv: "trace.export_csv",
  },
} as const;
