export type Severity = "INFO" | "WARNING" | "ERROR" | "CRITICAL";
export interface Reason { code: string; messageKey: string; severity: Severity; params: Record<string, unknown>; objectType?: string; objectId?: string; }
export interface Envelope<T> { ok: boolean; data: T; reasons: Reason[]; meta: { requestId: string; serverTime: string; configRevision?: number }; }
export interface AccountLineSpec { accountId: string; terminalFingerprint: string; templateId?: string; templateVersion?: string; sourceIds: string[]; instrumentIds: string[]; riskAmountPerOrder: number; desiredState: "READY_PAUSED" | "PAUSED" | "ACTIVE"; configRevision: number; appliedRevision: number; }
export interface AccountLineReadiness { accountId: string; desiredState: string; observedState: string; oneClickReady: boolean; blockers: Reason[]; warnings: Reason[]; nextAction: string | null; configRevision: number; appliedRevision: number; registryRevision: number; symbolSnapshotRevision: number; mappingRevision: number; matrixInputRevision: number; matrixRevision: number; runtimeBootId: string | null; lastReconciledAt: string; }
export interface AccountProvisioningStatus { jobId: string; accountId: string; state: string; checkpoint: string; desiredRevision: number; reasonCode: string | null; nextAction: string | null; }
export interface MatrixRow { sourceId: string; accountId: string; instrumentId: string; brokerSymbol: string | null; eligible: boolean; reasonCode: string | null; messageKey: string | null; inputRevisions: Record<string, number>; matrixRevision: number; }
export interface AccountLineClient { previewAdd(input: Partial<AccountLineSpec>): Promise<Envelope<unknown>>; applyAdd(input: Partial<AccountLineSpec> & { login: string; server: string; terminalFingerprint: string }): Promise<Envelope<AccountProvisioningStatus>>; readiness(accountId: string): Promise<Envelope<AccountLineReadiness>>; reconcile(accountId: string): Promise<Envelope<unknown>>; }
export interface FreshnessMeta { serverTime: string; dataAsOf: string; lastSuccessfulRefreshAt: string | null; staleAfterSeconds: number; isStale: boolean; }
export interface QueryScope { accountIds?: string[]; sourceIds?: string[]; canonicalInstrumentIds?: string[]; fromUtc: string; toUtc: string; timezone: string; preset?: "TODAY" | "YESTERDAY" | "LAST_7_DAYS" | "LAST_30_DAYS" | "MONTH_TO_DATE" | "CUSTOM"; }
export interface AiModelSummary { modelId: string; providerId: string; externalModelName: string; displayName: string; enabled: boolean; verificationState: string; configRevision: number; }
export interface AiRoutingSlot { slotId: string; providerId: string; modelId: string | null; order: number; }
export interface AiRoutingProfile { routingProfileId: string; displayName: string; slots: AiRoutingSlot[]; retryableAttemptLimitPerSlot: 5; primaryProbeIntervalSeconds: 60; allUnavailableCooldownSeconds: 60; routingState: string; }
export interface PromptVersion { promptVersionId: string; promptProfileId: string; versionNumber: number; state: "DRAFT" | "ACTIVE" | "RETIRED"; promptText: string; inputSchemaId: string; outputSchemaId: string; }
export interface HermesConfig { hermesConfigId: string; selectedTelegramSourceIds: string[]; aiRoutingProfileId: string | null; promptProfileId: string | null; state: "ENABLED" | "PAUSED" | "WAITING_INPUT" | "ARCHIVED"; authority: "OBSERVE_ONLY"; }
export interface SignalListQuery { scope: QueryScope; statuses?: string[]; side?: "BUY" | "SELL"; cursor?: string; limit: number; sort: "RECEIVED_AT_DESC" | "RECEIVED_AT_ASC"; }
export interface SignalListResponse<T = unknown> { items: T[]; nextCursor: string | null; freshness: FreshnessMeta; }
